### ISSUE TITLE
Issue mapping Auth0 authentication result with passport-auth0

### ISSUE THREAD

**Issue by skarlekar** [auth0/passport-auth0#62]
Hello, 

I am using passport-auth0 (Auth0 platform authentication strategy for Passport.js) to authenticate to my Hyperledger Fabric Composer REST server which uses Passport.js auth0 authentication strategy.

I am using the following lines for starting the composer-rest-server.

```
export COMPOSER_CARD=admin@smartapp-bna
export COMPOSER_NAMESPACES=always
export COMPOSER_AUTHENTICATION=true
export COMPOSER_TLS=true
export COMPOSER_WEBSOCKETS=true
export COMPOSER_PROVIDERS='{
  "auth0": {
    "provider": "auth0",
    "module": "passport-auth0",
    "domain": "smartapp.auth0.com",
    "clientID": "KBVVrYYF9V19...zAFNe4Tj7NRs8Woq",
    "clientSecret": "xNGbYZXdnQpqJQGw6...kJkTjnX-9W7OzQZn3mxsA2eC_ShPyAzzYd3nsT7Fj",
    "authPath": "/auth/auth0",
    "callbackURL": "/auth/auth0/callback",
    "successRedirect": "/",
    "failureRedirect": "/"
  }
}'
composer-rest-server
```

Authentication through Auth0 goes fine (logs at auth0 site shows login went through), but when the callback occurs the REST Server issues the following error.

It appears that what Auth0 provides needs to be properly mapped so that the REST server knows how to use it. Any help pointing me in the right direction will be appreciated. How do I go about doing the mapping?

> "ValidationError: The `user` instance is not valid. Details: `email` is invalid (value: \"676f6f676c652d6f617574683...com\").\n    at /home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/dao.js:1247:16\n    at user.<anonymous> (/home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/validations.js:589:13)\n    at user.next (/home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/hooks.js:93:12)\n    at done (/home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/validations.js:586:25)\n    at /home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/validations.js:664:7\n    at user.<anonymous> (/home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/validations.js:445:5)\n    at /home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/dao.js:2111:9\n    at /home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1012:9\n    at /home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16\n    at eachOfArrayLike (/home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:928:9)\n    at eachOf (/home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:990:5)\n    at _asyncMap (/home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1005:5)\n    at Object.map (/home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:995:16)\n    at allCb (/home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/dao.js:2025:13)\n    at /home/hyperuser/.nvm/versions/node/v8.10.0/lib/node_modules/composer-rest-server/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:512:7\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)"

**Comment by sakopov** [comment]
Have you been able to get Auth0 working with Composer API? I don't have the same problem, but a very similar one where the request goes thru Auth0 just fine, but the Composer REST API doesn't get the token and doesn't log any errors.

**Comment by joshcanhelp** [comment]
Outdated and no activity. Please let us know if you're still having this issue and we can look into it.
