### ISSUE TITLE
Throwing 'failed to obtain access token' when the exchange is actually successful.

### ISSUE THREAD

**Issue by RedTailBullet** [auth0/passport-auth0#68]
This happens recently that my back-end is throwing 'failed to obtain access token' error all over the place. I am passing an async function when initializing the strategy and that async function is called **WITH** the access token inside **AFTER** the error was thrown. I am so confused right now and basically, don't know what to do.

**Comment by RedTailBullet** [comment]
This is the error thrown BTW.

```{ InternalOAuthError: Failed to obtain access token
logger.ts:20
    at Strategy.OAuth2Strategy._createOAuthError (...\node_modules\passport-oauth2\lib\strategy.js:379:17)
    at ...\node_modules\passport-oauth2\lib\strategy.js:166:45
    at ...\node_modules\oauth\lib\oauth2.js:191:18
    at ClientRequest.<anonymous> (...\node_modules\oauth\lib\oauth2.js:162:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
  name: 'InternalOAuthError',
  message: 'Failed to obtain access token',
  oauthError: { Error: read ECONNRESET
    at TLSWrap.onread (net.js:622:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
  statusCode: 500 }```

**Comment by machuga** [comment]
Sorry to hear you're having issues! Did you happen to change a client id/secret recently? Or change something in your code or dashboard that we can try to understand?

**Comment by RedTailBullet** [comment]
Unfortunately, I haven't changed anything recently. Moreover, this issue only happens when I am testing my server locally on my windows machine. When I am testing it on my Linux machine everything seems to be fine.

**Comment by homerjam** [comment]
Upgrading 0.6.1 > 1.1.0 introduced silent failures into my otherwise working setup

**Comment by machuga** [comment]
@RedTailBullet Can you post the version of this package from the lock file on your windows server that is problematic?

**Comment by machuga** [comment]
@homerjam I'm sorry to hear that. We tried to represent the potential breaking change via the major version upgrade (v0.6.1 to v1). Are you receiving similar issues to this one?

**Comment by homerjam** [comment]
Yes, sorry I haven't had proper time to investigate. I looked through the commit history as I couldn't find a change log or migration guide and there didn't seem to be much to go on except the login_hint support. For now I've just rolled back. Is there any way to turn on some kind of debugging to find out why the failures are happening?

**Comment by machuga** [comment]
@homerjam I suspect it's due to our enforcement of State. You can try setting `state: false` in your config to see if that forces it back into its old behavior.

Here is the changeset: https://github.com/auth0/passport-auth0/compare/v0.6.1...v1.1.0

Here is the commit I suspect is responsible for your trouble: https://github.com/auth0/passport-auth0/commit/22c998957bedbe34ac7a7c40ecb02269ca179c5d

**Comment by joshcanhelp** [comment]
Outdated and no activity. Please let us know if you're still having this issue and we can look into it.
